algoritmo "Tabuada"
var
   contador, tabuada: inteiro
inicio
      escreva ("Quer a tabuada de quanto seu arrombado?")
      Leia(tabuada)
      contador <- 0
      escreval ("")
      enquanto contador < 11 faca
               escreval(tabuada," x",contador," =",tabuada*contador)
      contador <- contador+1
      fimenquanto
      escreval ("")
      escreval ("Terminei o que você precisa de algoritmo para resolver...")
fimalgoritmo