algoritmo "Divisão"
var
   contador, divisao: inteiro
inicio
      escreva ("Digite um número para eu dividir até 10:")
      Leia(divisao)
      contador <- 1
      escreval ("")
      enquanto contador < 11 faca
               escreval(divisao," /",contador," =",divisao/contador)
      contador <- contador+1
      fimenquanto
      escreval ("")
      escreval ("Terminei o que você precisa de algoritmo para resolver...")
fimalgoritmo