algoritmo "Soma"
var
   contador, soma: inteiro
inicio
      escreva ("Digite um número para somar até 100:")
      Leia(soma)
      contador <- 0
      escreval ("")
      enquanto contador < 101 faca
               escreval(soma," +",contador," =",soma+contador)
      contador <- contador+1
      fimenquanto
      escreval ("")
      escreval ("Terminei o que você precisa de algoritmo para resolver...")
fimalgoritmo